# Generated by Django 2.1.7 on 2019-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190223_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
