# Generated by Django 2.0 on 2017-12-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiblog', '0004_auto_20170703_1156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
